---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /q/metrics
    prometheus.io/port: "8080"
    prometheus.io/scheme: http
  labels:
    app.kubernetes.io/name: startpunkt
    app.kubernetes.io/version: 0.5.0
  name: startpunkt
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/version: 0.5.0
      app.kubernetes.io/name: startpunkt
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /q/metrics
        prometheus.io/port: "8080"
        prometheus.io/scheme: http
      labels:
        app.kubernetes.io/version: 0.5.0
        app.kubernetes.io/name: startpunkt
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: {{ .Values.app.image }}
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: {{ .Values.app.livenessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.app.livenessProbe.httpGet.path }}
              port: {{ .Values.app.ports.http }}
              scheme: {{ .Values.app.livenessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.livenessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.livenessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.livenessProbe.timeoutSeconds }}
          name: startpunkt
          ports:
            - containerPort: {{ .Values.app.ports.http }}
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: {{ .Values.app.readinessProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.app.readinessProbe.httpGet.path }}
              port: {{ .Values.app.ports.http }}
              scheme: {{ .Values.app.readinessProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.readinessProbe.periodSeconds }}
            successThreshold: {{ .Values.app.readinessProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.readinessProbe.timeoutSeconds }}
          startupProbe:
            failureThreshold: {{ .Values.app.startupProbe.failureThreshold }}
            httpGet:
              path: {{ .Values.app.startupProbe.httpGet.path }}
              port: {{ .Values.app.ports.http }}
              scheme: {{ .Values.app.startupProbe.httpGet.scheme }}
            initialDelaySeconds: {{ .Values.app.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.app.startupProbe.periodSeconds }}
            successThreshold: {{ .Values.app.startupProbe.successThreshold }}
            timeoutSeconds: {{ .Values.app.startupProbe.timeoutSeconds }}
      serviceAccountName: startpunkt
