name: Publish

concurrency:
  group: ci-pr
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    env:
      MVN: mvn --show-version --batch-mode
      CI: false

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: jdk17
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: mvn clean compile
        run: $MVN clean compile

      - name: mvn test -Pnative -Dquarkus.native.container-build=true
        run: $MVN test

      - name: mvn package -Pnative -DskipTests -Dquarkus.native.container-build=true
        run: $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@15560696de535e4014efeff63c48f16952e52dd1 # v6.2.0
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
