---
name: Pull Requests Build

concurrency:
  group: pr-build-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    env:
      MVN: mvn --show-version --batch-mode
      CI: false

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: â¤µï¸ Check out code from GitHub
        uses: actions/checkout@v4

      - name: ğŸ³ Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: â˜• Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: ğŸ§¹ Clean and Compile
        run: $MVN clean compile

      - name: ğŸ§ª Run Tests
        run: $MVN test --batch-mode --fail-at-end

      - name: ğŸ“„ Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: true

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: ğŸ“¡ SonarCloud Scan
        run: $MVN verify sonar:sonar -Dsonar.organization=magnus-ullberg -Dsonar.projectKey=magnus-ullberg_startpunkt -Dsonar.host.url=https://sonarcloud.io -Dsonar.branch.name=${{ steps.extract_branch.outputs.branch }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: ğŸ“¦ Package Native Application
        run: $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: ğŸ‹ Build and Push Docker Image
        id: build-and-push
        uses: docker/build-push-action@1ca370b3a9802c92e886402e0dd88098a2533b12 # v6.4.1
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
