name: Pull Requests Build

concurrency:
  group: ci-pr
  cancel-in-progress: false

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    env:
      MVN: mvn --show-version --batch-mode
      CI: false

    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write

    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4fd812986e6c8c2a69e18311145f9371337f27d4 # v3.4.0

      - name: jdk17
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "adopt"

      - name: mvn clean compile
        run: $MVN clean compile

      - name: mvn test
        run: $MVN test --batch-mode --fail-at-end
        
      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1
        with:
          fail_on_test_failures: true

      - name: mvn package -Pnative -DskipTests -Dquarkus.native.container-build=true
        run: $MVN package -Pnative -DskipTests -Dquarkus.native.container-build=true

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@1a162644f9a7e87d8f4b053101d1d9a712edc18c # v6.3.0
        with:
          context: .
          file: src/main/docker/Dockerfile.native-micro
          push: false
          cache-from: type=gha
          cache-to: type=gha,mode=max
